export const DESKTOP_OS = [
    'Windows 3.11',
    'Windows 95',
    'Windows 98',
    'Windows 2000',
    'Windows XP',
    'Windows Server 2003',
    'Windows Vista',
    'Windows 7',
    'Windows 8',
    'Windows 8.1',
    'Windows 10',
    'Windows ME',
    'Open BSD',
    'Sun OS',
    'Linux',
    'Mac OS',
    'QNX',
    'BeOS',
    'OS/2',
    'Chrome OS',
];

export const MOBILE_OS = ['iOS', 'Android OS', 'BlackBerry OS', 'Windows Mobile', 'Amazon OS'];

export const BROWSERS = {
    aol: 'AOL',
    edge: 'Edge',
    'edge-ios': 'Edge (iOS)',
    yandexbrowser: 'Yandex',
    kakaotalk: 'KKaoTalk',
    samsung: 'Samsung',
    silk: 'Silk',
    miui: 'MIUI',
    beaker: 'Beaker',
    'edge-chromium': 'Edge (Chromium)',
    chrome: 'Chrome',
    'chromium-webview': 'Chrome (webview)',
    phantomjs: 'PhantomJS',
    crios: 'Chrome (iOS)',
    firefox: 'Firefox',
    fxios: 'Firefox (iOS)',
    'opera-mini': 'Opera Mini',
    opera: 'Opera',
    ie: 'IE',
    bb10: 'BlackBerry 10',
    android: 'Android',
    ios: 'iOS',
    safari: 'Safari',
    facebook: 'Facebook',
    instagram: 'Instagram',
    'ios-webview': 'iOS (webview)',
    searchbot: 'Searchbot',
};